name: short_path
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  flutter_bloc:
  get_it:
  injectable:
  dio:
  device_info_plus: ^11.3.0
  flutter_expandable_fab:
  permission_handler: ^11.0.1
  url_launcher: ^6.1.7
  #  easy_pdf_viewer:
  syncfusion_flutter_pdfviewer: ^29.1.40
  retrofit:
  json_annotation: ^4.9.0
  awesome_dialog: ^3.2.1
  google_fonts:
  shared_preferences:
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  pull_down_button: ^0.10.2  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.10
  open_file: ^3.3.2
  path_provider: ^2.1.2
  cached_network_image:
  skeletonizer: ^2.0.1
  lottie:
  flutter_media_downloader:
  flutter_localization: ^0.3.0
  rxdart: ^0.27.0
  font_awesome_flutter:
  flutter_easyloading: ^3.0.5
  country_flags: ^3.2.0
  equatable:
  flutter_downloader:
  flutter_markdown:
  flutter_email_sender:
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  injectable_generator: ^2.4.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator:
  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/logo_splash.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true


  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/
    - assets/images/
    - assets/animations/loading_short.json
    - assets/animations/empty_list_animmation.json

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package