// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9kT-3i-969LQZgzD1ECbcR563QPBjs-Y',
    appId: '1:523637425611:web:3f5b2bbf6c7f7cc762624e',
    messagingSenderId: '523637425611',
    projectId: 'shortpath-687f9',
    authDomain: 'shortpath-687f9.firebaseapp.com',
    storageBucket: 'shortpath-687f9.firebasestorage.app',
    measurementId: 'G-1SL3DC9G0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSSBauQf1K7gTG2UXK3H8SfdCoyK5h20',
    appId: '1:523637425611:android:add85cffcca8f7f062624e',
    messagingSenderId: '523637425611',
    projectId: 'shortpath-687f9',
    storageBucket: 'shortpath-687f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr65hIxcGNap4Pe7J0v5Z_UkLOPhMQWw0',
    appId: '1:523637425611:ios:1d8e27c857f0702662624e',
    messagingSenderId: '523637425611',
    projectId: 'shortpath-687f9',
    storageBucket: 'shortpath-687f9.firebasestorage.app',
    iosBundleId: 'com.example.shortPath',
  );

}